title: NBUCore
description: Convenience macros, functions and API availability checks for iOS projects.
google_analytics: UA-40888254-2
show_downloads: true
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
